### ISSUE TITLE
Week 7 Roadmap

### ISSUE THREAD

**Issue by cyhsutw** [NoBetterThan97/twitter-api#12]
- [x] Gem and repo name (#13, #16)
- [x] Gem Structure
- [x] Environment variables for secret credentials
- [x] Command-line application for your gem
- [x] Continuous Integration (#14, #15)
- [x] Gemspec

**Comment by cyhsutw** [comment]
Regarding the repo name and gem name, what do you think about `tweetsearch`?

**Comment by Leoli0320** [comment]
twweetsearch 可以啊！
